posts:          /actualites/:year/:month/:day/:slug/
categories:     /actualites/:slug/
persons:        /equipe/:slug/
organizations:  /tierces-parties/:slug/
authors:        /equipe/:slug/actualites/
teachers:       /equipe/:slug/programs/
researchers:    /equipe/:slug/articles/
