categories: /actualites/:slug/
posts: /actualites/:year/:month/:day/:slug/
diplomas: /diplomes/:slug/
programs: /offre-de-formation/:slug/
organizations: /tierces-parties/:slug/
persons: /equipe/:slug/
authors: /equipe/:slug/actualites/
researchers: /equipe/:slug/papers/
teachers: /equipe/:slug/programs/
