baseURL: /

## LANGUAGE
defaultContentLanguage: fr
defaultContentLanguageInSubdir: true

## DEUXFLEURS
deployment:
  targets:
    - name: "production"
      URL: "s3://example.osuny.org?endpoint=https://garage.deuxfleurs.fr&awssdk=v2&use_path_style=true&region=garage&disable_https=false"
