params:
  cdnkey: https://osuny-1b4da.kxcdn.com
  cookie_banner:
    enable: false
    blank: true
    page: https://gdpr.eu/cookies/
baseURL: /
defaultContentLanguage: fr
languageCode: fr
languages:
  fr:
    title: Osuny template
theme: osuny-hugo-theme
paginate: 18
permalinks:
  posts:          /actualites/:year/:month/:day/:slug/
  categories:     /actualites/:sections/:slug/
  persons:        /equipe/:slug/
  authors:        /equipe/:slug/actualites/
  administrators: /equipe/:slug/administration/
  researchers:    /equipe/:slug/publications/
  teachers:       /equipe/:slug/formations/
taxonomies:
  administrator:  administrators
  author:         authors
  category:       categories
  researcher:     researchers
  teacher:        teachers
